/*
 * Tests for the direct-control role classifier (pure/Actuation.cs) — the capability→actuation mapping
 * the Actuator glue acts on. Pinned against the REAL Crew-2 stack part names from data/craftdump.csv, so
 * a wrong role (lighting the wrong engine set, dropping the trunk instead of S2) is caught headless, not
 * discovered by a lost flight.
 *
 * REGRESSION carried up from VehiclePartsTest (flight_0822_201219): liftoff must light ONLY the octaweb
 * all-engines mode. Here that is stated at the role level: EngineLightsFor(octaweb, "AllEngines", OctawebAll)
 * true, and the Three/Centre modes AND the pod/MVac all false for the liftoff command.
 *
 * ---- W2 NOTES ON THE RESTORED HALF (2026-09-04) - read before trusting the constants below ----
 * (1) THE DUMP MOVED. The header above and the comment on the constants say "data/craftdump.csv"; that path
 *     was deleted with the autopilot. The dump is now `docs/reference/craftdump.csv`, regenerated by W0
 *     (§B16.4). The constants themselves were NOT edited - restoring, not rewriting, is W2's job.
 * (2) THREE OF THE PINNED NAMES ARE NOT IN THE CURRENT DUMP, and that is expected, not a defect. The dump is
 *     a WORK IN PROGRESS with 20 parts and is missing the drogues, the mains, the trunk adapter/decoupler and
 *     the S2 RCS thrusters (§B12.7 / §B16.4; a RE-DUMP IS PENDING). So LEGS ("KRE-FalconLegMk2-M", vs the
 *     dump's present "KRE-FalconLeg-M"), DROGUES and MAINS are names this file pinned at `8b81816^` and the
 *     current dump cannot confirm. Every assertion that uses them is a CLASSIFIER assertion - "this name
 *     carries no engine/decoupler role" - which is true of the name whether or not the part is on the craft,
 *     so they are left exactly as restored. §1.4: no part name was invented, corrected or guessed here.
 * (3) WHAT *IS* CONFIRMED AGAINST THE LIVE DUMP is the W2 section at the bottom of this file, which reads
 *     `docs/reference/craftdump.csv` off disk and asserts §B16.4's hard assertion against it.
 */
using DragonScreen;
using System;

public static class ActuationTest
{
    static int checks = 0, failures = 0;
    static void Check(string what, bool ok, string detail)
    {
        checks++;
        if (!ok) { failures++; Console.WriteLine("  FAIL  " + what + "   " + detail); }
    }

    // ---- the real part names (data/craftdump.csv, col 2) ----
    const string OCTAWEB   = "TE.19.F9.S1.Engine";
    const string MVAC      = "TE.19.F9.S2.Engine";
    const string POD       = "TE.18.DRAGONV2.POD";
    const string INTERSTAGE= "TE.19.F9.S1.Interstage";
    const string DRAGONDEC = "TE.19.C.Dragon.Decoupler";
    const string TRUNK     = "TE.18.DRAGONV2.TRUNK";
    const string ERECTOR   = "TE.Ghidorah.Erector";
    const string LEGS      = "KRE-FalconLegMk2-M";
    const string FINS      = "Grid Fin M Titanium";
    const string DROGUES   = "TE.CD2.POD.DROGUES";
    const string MAINS     = "TE.CD2.POD.MAINS";

    // real octaweb engineIDs (RO_TE_Falcon_9.cfg)
    const string ALL = "AllEngines", THREE = "ThreeLanding", CENTRE = "CenterOnly";

    public static int Run()
    {
        Console.WriteLine("DragonScreen direct-control role classifier tests");

        // ---- octaweb: engineID picks the mode ----
        Check("octaweb AllEngines  -> OctawebAll",    Actuation.EngineRoleOf(OCTAWEB, ALL)    == EngineRole.OctawebAll, "");
        Check("octaweb ThreeLanding-> OctawebThree",  Actuation.EngineRoleOf(OCTAWEB, THREE)  == EngineRole.OctawebThree, "");
        Check("octaweb CenterOnly  -> OctawebCentre", Actuation.EngineRoleOf(OCTAWEB, CENTRE) == EngineRole.OctawebCentre, "");

        // ---- MVac + pod SuperDraco ----
        Check("MVac (any id)   -> SecondStage", Actuation.EngineRoleOf(MVAC, "Engine") == EngineRole.SecondStage, "");
        Check("MVac (blank id) -> SecondStage", Actuation.EngineRoleOf(MVAC, "")       == EngineRole.SecondStage, "");
        Check("pod engine      -> PodAbort (SuperDraco)", Actuation.EngineRoleOf(POD, "Engine") == EngineRole.PodAbort, "");

        // ---- THE LIFTOFF GATE: only the all-engines mode lights (flight_0822 tank-cook regression) ----
        Check("liftoff lights octaweb AllEngines",
              Actuation.EngineLightsFor(OCTAWEB, ALL, EngineRole.OctawebAll), "");
        Check("liftoff does NOT light ThreeLanding  [the bug]",
              !Actuation.EngineLightsFor(OCTAWEB, THREE, EngineRole.OctawebAll), "");
        Check("liftoff does NOT light CenterOnly    [the bug]",
              !Actuation.EngineLightsFor(OCTAWEB, CENTRE, EngineRole.OctawebAll), "");
        Check("liftoff does NOT light the MVac",
              !Actuation.EngineLightsFor(MVAC, "", EngineRole.OctawebAll), "");
        Check("liftoff does NOT light the SuperDraco",
              !Actuation.EngineLightsFor(POD, "Engine", EngineRole.OctawebAll), "");

        // ---- SES-1: only the MVac lights ----
        Check("SES-1 lights the MVac",           Actuation.EngineLightsFor(MVAC, "", EngineRole.SecondStage), "");
        Check("SES-1 does NOT light the octaweb", !Actuation.EngineLightsFor(OCTAWEB, ALL, EngineRole.SecondStage), "");
        Check("SES-1 does NOT light the SuperDraco", !Actuation.EngineLightsFor(POD, "Engine", EngineRole.SecondStage), "");

        // ---- abort: only the pod SuperDraco lights ----
        Check("abort lights the pod SuperDraco",  Actuation.EngineLightsFor(POD, "Engine", EngineRole.PodAbort), "");
        Check("abort does NOT light the octaweb", !Actuation.EngineLightsFor(OCTAWEB, ALL, EngineRole.PodAbort), "");
        Check("abort does NOT light the MVac",    !Actuation.EngineLightsFor(MVAC, "", EngineRole.PodAbort), "");

        // ---- non-engine parts carry no engine role ----
        Check("legs   -> no engine role", Actuation.EngineRoleOf(LEGS, "")    == EngineRole.None, "");
        Check("fins   -> no engine role", Actuation.EngineRoleOf(FINS, "")    == EngineRole.None, "");
        Check("drogues-> no engine role", Actuation.EngineRoleOf(DROGUES, "") == EngineRole.None, "");

        // ---- decouplers: each real part maps to exactly one role ----
        Check("interstage -> StageSep",       Actuation.DecouplerRoleOf(INTERSTAGE) == DecouplerRole.StageSep, "");
        Check("dragon dec -> DragonSep",      Actuation.DecouplerRoleOf(DRAGONDEC)  == DecouplerRole.DragonSep, "");
        Check("trunk      -> TrunkJettison",  Actuation.DecouplerRoleOf(TRUNK)      == DecouplerRole.TrunkJettison, "");
        Check("erector    -> Erector",        Actuation.DecouplerRoleOf(ERECTOR)    == DecouplerRole.Erector, "");

        // ---- ⛔ the dangerous confusions SeparateDragon / trunk-jettison depend on being distinct ----
        Check("SECO drops S2, NOT the trunk (dragon dec != TrunkJettison)",
              Actuation.DecouplerRoleOf(DRAGONDEC) != DecouplerRole.TrunkJettison, "");
        Check("trunk jettison is NOT the Dragon decoupler (trunk != DragonSep)",
              Actuation.DecouplerRoleOf(TRUNK) != DecouplerRole.DragonSep, "");
        Check("erector is NOT a stage-sep decoupler (erector != StageSep)",
              Actuation.DecouplerRoleOf(ERECTOR) != DecouplerRole.StageSep, "");

        // ---- non-decoupler parts carry no decoupler role ----
        Check("pod     -> no decoupler role", Actuation.DecouplerRoleOf(POD)     == DecouplerRole.None, "");
        Check("octaweb -> no decoupler role", Actuation.DecouplerRoleOf(OCTAWEB) == DecouplerRole.None, "");
        Check("legs    -> no decoupler role", Actuation.DecouplerRoleOf(LEGS)    == DecouplerRole.None, "");
        Check("mains   -> no decoupler role", Actuation.DecouplerRoleOf(MAINS)   == DecouplerRole.None, "");

        // ================================================================================================
        // ---- W2 (2026-09-04): §B16.4's HARD ASSERTION, guarded against the REAL dump on disk ----
        // ================================================================================================
        // §B16.4 requires the booster binding to assert EXACTLY ONE octaweb, that it is the Tundra one, and
        // to REJECT any KK_SPX / KK_F9demo part - and requires that assertion to be "GUARDED BY A TEST (the
        // recovered test/ActuationTest.cs pattern: assert the capability map against the real dump, headless)".
        // That is this section. The decision logic is pure/OctawebBinding.cs; here it is exercised BOTH ways:
        // against the actual craft dump, and against synthetic name sets for the three refusal paths (which
        // the dump cannot show, because the failure it guards has not happened yet).
        RunDumpAssertions();

        Console.WriteLine("  " + checks + " checks, " + failures + " failed");
        return failures > 0 ? 1 : 0;
    }

    // Where the repo's craft dump is, relative to the test exe (plugin/build/DragonScreenTest.exe):
    // ".." = plugin/ , "../.." = the repo root. Same locate-by-assembly idiom LayoutTest.cs already uses.
    static string DumpPath()
    {
        return System.IO.Path.GetFullPath(System.IO.Path.Combine(
            System.IO.Path.GetDirectoryName(
                System.Reflection.Assembly.GetExecutingAssembly().Location),
            "..", "..", "docs", "reference", "craftdump.csv"));
    }

    static void RunDumpAssertions()
    {
        // ---- the three REFUSAL paths, on synthetic name sets (no dump needed, and none possible) ----
        string bound;

        // (a) the nominal craft: our octaweb once, nothing foreign -> Ok, and it hands back the name.
        string[] nominal = { POD, TRUNK, INTERSTAGE, OCTAWEB, MVAC, DRAGONDEC, ERECTOR };
        Check("bind: nominal craft -> Ok",
              OctawebBinding.Bind(nominal, out bound) == OctawebBind.Ok, "");
        Check("bind: Ok hands back the octaweb part name", bound == OCTAWEB, "bound=" + (bound ?? "null"));
        Check("bind: a successful bind is silent (no annunciation)",
              OctawebBinding.Annunciation(OctawebBind.Ok) == null, "");

        // (b) no octaweb at all (e.g. post-MECO, Dragon only) -> NotFound, refuse + annunciate.
        string[] noBooster = { POD, TRUNK, MVAC, DRAGONDEC };
        Check("bind: no octaweb -> NotFound",
              OctawebBinding.Bind(noBooster, out bound) == OctawebBind.NotFound, "");
        Check("bind: NotFound binds nothing", bound == null, "bound=" + (bound ?? "null"));
        Check("bind: null part list -> NotFound (never a null-ref in a controller tick)",
              OctawebBinding.Bind(null, out bound) == OctawebBind.NotFound, "");
        Check("bind: empty part list -> NotFound",
              OctawebBinding.Bind(new string[0], out bound) == OctawebBind.NotFound, "");

        // (c) TWO octawebs -> Ambiguous. THE WHOLE POINT: it must NOT pick one.
        string[] twoOctawebs = { OCTAWEB, MVAC, OCTAWEB };
        Check("bind: two octawebs -> Ambiguous",
              OctawebBinding.Bind(twoOctawebs, out bound) == OctawebBind.Ambiguous, "");
        Check("bind: Ambiguous refuses to pick one", bound == null, "bound=" + (bound ?? "null"));

        // (d) the Kartoffelkuchen Falcon 9 (installed 2026-09-03) -> ForeignVehicle, in BOTH prefixes, and
        // EVEN WHEN OUR OWN OCTAWEB IS ALSO PRESENT - the mixed case is exactly where picking is wrong.
        Check("bind: KK_SPX octaweb alone -> ForeignVehicle",
              OctawebBinding.Bind(new[] { "KK_SPX_F9_Octaweb", "KK_SPX_F9_S1" }, out bound) == OctawebBind.ForeignVehicle, "");
        Check("bind: KK_F9demo part -> ForeignVehicle",
              OctawebBinding.Bind(new[] { "KK_F9demo_Octaweb" }, out bound) == OctawebBind.ForeignVehicle, "");
        Check("bind: OUR octaweb + a KK part -> still ForeignVehicle  [the mixed-craft trap]",
              OctawebBinding.Bind(new[] { OCTAWEB, MVAC, "KK_SPX_F9_Octaweb" }, out bound) == OctawebBind.ForeignVehicle, "");
        Check("bind: ForeignVehicle binds nothing", bound == null, "bound=" + (bound ?? "null"));
        Check("bind: foreign marker match is case-insensitive",
              OctawebBinding.IsForeignBoosterPart("kk_spx_f9_octaweb")
              && OctawebBinding.IsForeignBoosterPart("KK_F9DEMO_S1"), "");
        Check("bind: our own parts are not foreign",
              !OctawebBinding.IsForeignBoosterPart(OCTAWEB) && !OctawebBinding.IsForeignBoosterPart(POD), "");

        // Every refusal must SAY which one it was - "refuse and annunciate", not refuse silently.
        Check("bind: NotFound annunciates",
              !string.IsNullOrEmpty(OctawebBinding.Annunciation(OctawebBind.NotFound)), "");
        Check("bind: Ambiguous annunciates",
              !string.IsNullOrEmpty(OctawebBinding.Annunciation(OctawebBind.Ambiguous)), "");
        Check("bind: ForeignVehicle annunciates",
              !string.IsNullOrEmpty(OctawebBinding.Annunciation(OctawebBind.ForeignVehicle)), "");

        // IDENTITY IS THE WHOLE NAME, not a marker. KK's octaweb also ends in "Octaweb"; a substring test
        // would match both, which is the failure this exists to prevent.
        Check("bind: identity is the whole part name, not a substring",
              OctawebBinding.IsTundraOctaweb(OCTAWEB)
              && !OctawebBinding.IsTundraOctaweb("KK_SPX_F9_Octaweb")
              && !OctawebBinding.IsTundraOctaweb("TE.19.F9.S1.Engine.Extra"), "");

        // §B16.4 step 1 records that IsBooster still discriminates because no KK name contains ".S1.".
        // Assert that about OUR classifier, against the name §B16.4 states the pack ships.
        Check("IsBooster accepts our octaweb", VehicleParts.IsBooster(OCTAWEB), "");
        Check("IsBooster rejects the KK octaweb (no '.S1.' in it)",
              !VehicleParts.IsBooster("KK_SPX_F9_Octaweb"), "");

        // ================================================================================================
        // ---- OCT1 (2026-09-05): THE GLUE'S NAME SOURCE IS PART OF THE CONTRACT ----
        // ================================================================================================
        // WHAT HAPPENED. Two functions read the SAME field, `Part.name`, in the same part walk, and
        // disagreed about one vessel: `BoosterHost.Describe` -> `VehicleParts.IsBooster` (a `.S1.`
        // SUBSTRING) passed, while `OctawebEngines.Resolve` -> `IsTundraOctaweb` (whole-name EQUALITY)
        // failed. "Found the booster" + "OCTAWEB NOT FOUND", 264 times, zero successes: booster attitude
        // uncommanded for 222 rows of LandingBurn and a touchdown 511 km off the deck.
        //
        // WHY NO TEST CAUGHT IT. This suite feeds the pure layer names from `docs/reference/craftdump.csv`,
        // which `CraftDump.cs:60` writes from `partInfo.name` — the CLEAN name. The live glue fed `p.name`.
        // The pure layer and its test agreed with each other and both disagreed with the game. A pure test
        // cannot see a glue bug, so what is pinned here is the CONTRACT the glue must satisfy: a decorated
        // name — the same identity carrying extra characters — is NOT this octaweb, and the two classifiers
        // MUST NOT be able to disagree about one.
        //
        // ⚠ THE EXACT LIVE STRING IS NOT YET MEASURED. `Trim()` was already applied and did not help, so it
        // is not surrounding whitespace; beyond that nothing is proven, and nothing is assumed here. The
        // diagnostic that will measure it is in `OctawebEngines.Resolve` (it prints both name sources
        // escaped, with lengths, once via LogGate) and it needs a flight — a separate owner gate. When the
        // string lands, ADD IT to the array below verbatim; the family it belongs to is already refused.
        //
        // ⛔ THE FIX IS NEVER TO RELAX `IsTundraOctaweb` TO A SUBSTRING. §B16.4 requires REFUSING rather
        // than mis-binding the Kartoffelkuchen `KK_SPX` octaweb, and a substring test is exactly how that
        // protection is lost. Exactness is the point; the glue is what had to change.
        string[] decorated =
        {
            OCTAWEB + "_4293186206",     // the craft file's own form (docs/reference/Crew-2.craft:5668)
            OCTAWEB + " (Clone)",        // a Unity-instantiated object name
            OCTAWEB + "(Clone)",
            OCTAWEB + " 4293186206",
            "TE.19.F9​.S1.Engine", // a ZERO-WIDTH SPACE inside the name - invisible in any log line
            "0:" + OCTAWEB,              // extras need not be a suffix, and are not assumed to be one
        };
        for (int i = 0; i < decorated.Length; i++)
        {
            string d = decorated[i];
            Check("OCT1: a decorated octaweb name is NOT the Tundra octaweb  [" + d + "]",
                  !OctawebBinding.IsTundraOctaweb(d), "");
            Check("OCT1: ...yet IsBooster still accepts it  [" + d + "]  <- THE DISAGREEMENT",
                  VehicleParts.IsBooster(d), "");
            Check("OCT1: a vessel whose only octaweb is decorated binds NOTHING  [" + d + "]",
                  OctawebBinding.Bind(new[] { POD, TRUNK, d, MVAC }, out bound) == OctawebBind.NotFound,
                  "");
            Check("OCT1: ...and hands back no part  [" + d + "]", bound == null, "bound=" + (bound ?? "null"));
        }

        // The other half of the contract: the name the dumps actually write binds, and binds cleanly. If
        // the glue feeds THIS, the two classifiers cannot disagree — which is the whole of OCT1's fix.
        Check("OCT1: the dump's own name (partInfo.name) binds Ok",
              OctawebBinding.Bind(new[] { POD, TRUNK, OCTAWEB, MVAC }, out bound) == OctawebBind.Ok, "");
        Check("OCT1: ...and both classifiers agree on it",
              VehicleParts.IsBooster(OCTAWEB) && OctawebBinding.IsTundraOctaweb(OCTAWEB), "");

        // WHY "extra characters, but NOT surrounding whitespace" is a PROVEN narrowing and not a guess:
        // `IsTundraOctaweb` Trim()s, and Trim() reaches Unicode spaces too. A name padded with a
        // NON-BREAKING space still binds - so whatever the live string carried, padding was not it.
        Check("OCT1: Trim() already covers whitespace padding (which is why it did not help)",
              OctawebBinding.IsTundraOctaweb(" " + OCTAWEB + " "), "");

        // ---- and now against the REAL dump on disk ----
        string path = DumpPath();
        if (!System.IO.File.Exists(path))
        {
            // A missing dump is a FAILURE, not a skip: §B16.4's C7 status is "SATISFIED - the dump is in
            // the repo", and this assertion is worthless if it silently passes without one.
            Check("craft dump is present in the repo (docs/reference/craftdump.csv)", false, path);
            return;
        }

        string[] lines = System.IO.File.ReadAllLines(path);
        Check("dump has a header and rows", lines.Length > 1, "lines=" + lines.Length);

        // Split on ',' is SAFE BY CONSTRUCTION, not by luck: CraftDump.C() replaces every ',' in a value
        // with ';' before writing it (plugin/src/CraftDump.cs:185), so no field can contain a comma.
        string[] head = lines[0].Split(',');
        Check("dump column 0 is part_idx", head.Length > 1 && head[0] == "part_idx", lines[0]);
        Check("dump column 1 is part_name", head.Length > 1 && head[1] == "part_name", lines[0]);
        Check("dump column 6 is kind", head.Length > 6 && head[6] == "kind", lines[0]);
        Check("dump column 7 is name", head.Length > 7 && head[7] == "name", lines[0]);
        Check("dump column 11 is extra", head.Length > 11 && head[11] == "extra", lines[0]);
        int cols = head.Length;

        var partNames = new System.Collections.Generic.List<string>();
        var seen = new System.Collections.Generic.List<string>();
        var octawebEngineIds = new System.Collections.Generic.List<string>();
        int ragged = 0, engineModuleRows = 0;
        for (int i = 1; i < lines.Length; i++)
        {
            if (lines[i].Length == 0) continue;
            string[] f = lines[i].Split(',');
            if (f.Length != cols) { ragged++; continue; }
            string name = f[1];
            if (!seen.Contains(name)) { seen.Add(name); partNames.Add(name); }   // one entry per part name

            bool isEngineModule = f[6] == "MODULE"
                && (f[7] == "ModuleEnginesRF" || f[7] == "ModuleEngines");
            if (!isEngineModule) continue;
            engineModuleRows++;
            if (!OctawebBinding.IsTundraOctaweb(name)) continue;
            const string tag = "engineID=";
            int at = f[11].IndexOf(tag, StringComparison.Ordinal);
            if (at >= 0) octawebEngineIds.Add(f[11].Substring(at + tag.Length).Trim());
        }
        Check("every dump row has the header's column count", ragged == 0, "ragged=" + ragged);
        Check("the dump lists engine modules at all", engineModuleRows > 0, "");

        // THE ASSERTION ITSELF, against the real vessel's part names.
        string dumpBound;
        OctawebBind verdict = OctawebBinding.Bind(partNames.ToArray(), out dumpBound);
        Check("REAL DUMP: the octaweb binding asserts Ok",
              verdict == OctawebBind.Ok, "verdict=" + verdict + " over " + partNames.Count + " part names");
        Check("REAL DUMP: it binds the Tundra octaweb", dumpBound == OctawebBinding.TundraOctawebPart,
              "bound=" + (dumpBound ?? "null"));
        Check("REAL DUMP: no KK_SPX / KK_F9demo part is present", !HasForeign(partNames), "");

        // Exactly one octaweb PART, carrying exactly the THREE engineIDs §B16.4 names - once each.
        Check("REAL DUMP: the octaweb carries exactly 3 engine modules",
              octawebEngineIds.Count == 3, "found=" + octawebEngineIds.Count + " [" + Join(octawebEngineIds) + "]");
        Check("REAL DUMP: engineID AllEngines present exactly once",
              CountOf(octawebEngineIds, OctawebBinding.EngineIdAll) == 1, Join(octawebEngineIds));
        Check("REAL DUMP: engineID ThreeLanding present exactly once",
              CountOf(octawebEngineIds, OctawebBinding.EngineIdThreeLanding) == 1, Join(octawebEngineIds));
        Check("REAL DUMP: engineID CenterOnly present exactly once",
              CountOf(octawebEngineIds, OctawebBinding.EngineIdCenterOnly) == 1, Join(octawebEngineIds));

        // NEVER BY ENGINE-PART COUNT (§B16.4 / VehicleParts.cs:37): OctawebEngineCount = 9 is NOZZLES.
        // Prove the deleted "expect 9 engine parts" procedure would fail on the real craft.
        Check("REAL DUMP: the octaweb is ONE part with 3 modes, not " + VehicleParts.OctawebEngineCount + " engine parts",
              octawebEngineIds.Count != VehicleParts.OctawebEngineCount, "");

        // And the classifier maps each real engineID to the right role - the dump strings, not our markers.
        for (int i = 0; i < octawebEngineIds.Count; i++)
        {
            string id = octawebEngineIds[i];
            EngineRole want =
                  id == OctawebBinding.EngineIdAll ? EngineRole.OctawebAll
                : id == OctawebBinding.EngineIdThreeLanding ? EngineRole.OctawebThree
                : id == OctawebBinding.EngineIdCenterOnly ? EngineRole.OctawebCentre
                : EngineRole.None;
            Check("REAL DUMP: engineID '" + id + "' is a known octaweb mode", want != EngineRole.None, "");
            Check("REAL DUMP: EngineRoleOf(octaweb, '" + id + "') -> " + want,
                  Actuation.EngineRoleOf(OctawebBinding.TundraOctawebPart, id) == want, "");
        }
    }

    static bool HasForeign(System.Collections.Generic.List<string> names)
    {
        for (int i = 0; i < names.Count; i++)
            if (OctawebBinding.IsForeignBoosterPart(names[i])) return true;
        return false;
    }

    static int CountOf(System.Collections.Generic.List<string> xs, string want)
    {
        int n = 0;
        for (int i = 0; i < xs.Count; i++) if (xs[i] == want) n++;
        return n;
    }

    static string Join(System.Collections.Generic.List<string> xs)
    {
        return string.Join(" ", xs.ToArray());
    }
}
